# Generated by Django 2.2.7 on 2024-12-15 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('volunteer', '0001_initial'),
        ('bookmark', '0001_initial'),
        ('event', '0001_initial'),
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkmodel',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='event.Event', verbose_name='event'),
        ),
        migrations.AddField(
            model_name='bookmarkmodel',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='organisation.Organisation', verbose_name='organisation'),
        ),
        migrations.AddField(
            model_name='bookmarkmodel',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='volunteer.Volunteer', verbose_name='volunteer'),
        ),
    ]
