# Generated by Django 2.2.7 on 2024-12-15 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('location', models.TextField(max_length=50, verbose_name='location')),
                ('facebook', models.URLField(blank=True, max_length=100, null=True, verbose_name='facebook')),
                ('instagram', models.URLField(blank=True, max_length=100, null=True, verbose_name='instagram')),
                ('linkedin', models.URLField(blank=True, max_length=100, null=True, verbose_name='LinkedIn')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='volunteers/profile_pictures', verbose_name='profile picture')),
                ('privacy_setting', models.CharField(choices=[('public', 'public'), ('private', 'private'), ('controlled', 'controlled'), ('secret', 'secret')], default='private', max_length=100, verbose_name='privacy setting')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
