# Generated by Django 2.2.7 on 2024-12-15 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('type', models.CharField(choices=[('Non-profit organisation', 'Non-profit organisation'), ('Project', 'Project')], default='Non-profit organisation', max_length=100, verbose_name='type')),
                ('privacy_setting', models.CharField(choices=[('public', 'public'), ('private', 'private'), ('controlled', 'controlled'), ('secret', 'secret')], default='private', max_length=100, verbose_name='Privacy setting')),
                ('profile_pic', models.ImageField(blank=True, upload_to='media-files/organisation/images', verbose_name='image')),
                ('facebook', models.URLField(blank=True, max_length=100, null=True, verbose_name='facebook')),
                ('instagram', models.URLField(blank=True, max_length=100, null=True, verbose_name='instagram')),
                ('linkedin', models.URLField(blank=True, max_length=100, null=True, verbose_name='LinkedIn')),
                ('document', models.FileField(blank=True, null=True, upload_to='media-files/organisation/file', verbose_name='document')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(verbose_name='description')),
                ('website', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('terms_of_services', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organisation', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
